name: TOOLBOXLAP-Linux

on:
  workflow_dispatch:

jobs:
  setup-ssh-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Download and install Playit
      run: |
        curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit

    - name: Set SSH password for runner
      run: |
        echo "runner:admin@123" | sudo chpasswd
        sudo systemctl restart ssh

    - name: Start Playit tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup ./playit --secret "$PLAYIT_AUTH_KEY" &

    - name: Keep the GitHub Action Runner Alive
      run: sleep 21600  # 6 hours
